version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - connection
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: facilita_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - connection
    restart: always

networks:
  connection:
    driver: bridge